### PR TITLE
feat: bump `doctrine/dbal` version constraint to allow `^4.0`

### PR DESCRIPTION
**Pull request by romm**

### CODE REVIEW

**Comment by Mediagone** [comment]
The `getVarcharTypeDeclarationSQL` deprecation and the new `getStringTypeDeclarationSQL` method (AbstractPlatform) were introduced in 3.4.0, so the minimum requirement should also be updated in composer.json (=> `"doctrine/dbal": "^3.4|^4.0",`)

**Comment by romm** [comment]
Should we drop support for `doctrine/dbal:^2.7`? We can also call `getVarcharTypeDeclarationSQL` if the method exists, for backward compatibility.

**Comment by Mediagone** [comment]
Ok for the conditional call to `getVarcharTypeDeclarationSQL`, we'll think about dropping the 2.7 support later :)

**Comment by romm** [comment]
Done!

**Comment by Mediagone** [comment]
Thanks, but I would prefer to have a clear conditional branch with two distinct method calls rather than using a dynamic call, since the string usage degrades the readability and code navigation.

**Pull request merged**
